name: bad-cicd
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  POSTGRES_DB: ci
  POSTGRES_USER: ci
  POSTGRES_PASSWORD: ci
  POSTGRES_HOST: db_server
  POSTGRES_PORT: 5432
  NODE_ENV: ci
  SERVER_USER: c29-bad-grp3
  SERVER_HOST: c29-bad-grp3.yodaandkeungjai.com

jobs:
  test: 
  deploy:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: check connection to server
        run: |
          mkdir -p ~/.ssh
          cd ~/.ssh
          ssh keyscan ${{env.SERVER_HOST}} >> ~/.ssh/known_hosts
          echo ${{secrets.SSH_PRIVATE_KEY}} > key.pem
          chmod 400 key.pem
          ssh -i key.pem ${{env.SERVER_USER}}@${{env.SERVER_HOST}}
          